---
  - name: install the package
    yum:
      name: "{{ package }}"
      state: latest
   
  - name: start the service service
    service:
      name: "{{ service }}"
      state: "{{ svc_state }}"
